6013 skynet page structure
Interfirst/AutomationTestsCore pull request #5
Opened 2021-09-16 13:10 UTC by im-ayakovtsov

added switching by tabs on pages

2021-09-16 13:34 UTC, im-obondaruk requested changes

2021-09-16 13:34 UTC, im-obondaruk commented on cypress/src/skynet/pages/myAccountPage.js
> +      .should('not.be.disabled')
No assertions in the pages.

2021-09-16 13:34 UTC, im-obondaruk commented on cypress/src/skynet/po.js
>    navigationBar: {
Maybe we could call the fragment sideNavBar, and let it be on the first level of fragments' object properties?

2021-09-16 13:34 UTC, im-obondaruk commented on cypress/src/skynet/po.js
> +  formFragment: {
Let's discuss this level of fragments

2021-09-16 13:34 UTC, im-obondaruk commented on cypress/src/skynet/sharedFragments/formFragment.js
> +      .should('not.be.disabled')
No assertion in the page class

2021-09-16 13:34 UTC, im-obondaruk commented on cypress/src/skynet/sharedFragments/navbarFragment.js
> +    return cy.get(`[data-test=${value}]`)
locator should be in the constructor. Make it a function that returns a string depend on what value you've passed.
`this.companyElem = (companyValue) => "[data-test=${value}]"`

2021-09-16 13:34 UTC, im-obondaruk commented on cypress/src/skynet/sharedFragments/navbarFragment.js
> +    return cy.get(`[data-test=${value}]`)
locator should be as a function in constructor.

2021-09-17 08:56 UTC, closed without merging

2021-09-17 08:57 UTC, im-ayakovtsov commented
Will be improved in the new PR